- name: project.models.readonly
  note: Module project Type Object models grant readonly
- name: project.models.nodrop
  note: Module project Type Object models grant nodrop
- name: project.models.full
  note: Module project Type Object models grant full
- name: project.models.crw
  note: Module project Type Object models grant crw
