- name: le.models.readonly
  note: Module le Type Object models grant readonly
  parent_id: null
- name: le.models.nodrop
  note: Module le Type Object models grant nodrop
  parent_id: null
- name: le.models.full
  note: Module le Type Object models grant full
  parent_id: null
- name: le.models.crw
  note: Module le Type Object models grant crw
  parent_id: null
