- name: wkf_srm.models.readonly
  note: Module wkf_srm Type Object models grant readonly
- name: wkf_srm.models.nodrop
  note: Module wkf_srm Type Object models grant nodrop
- name: wkf_srm.models.full
  note: Module wkf_srm Type Object models grant full
- name: wkf_srm.models.crw
  note: Module wkf_srm Type Object models grant crw
