- name: bc.models.readonly
  note: Module bc Type Object models grant readonly
  parent_id: null
- name: bc.models.nodrop
  note: Module bc Type Object models grant nodrop
  parent_id: null
- name: bc.models.full
  note: Module bc Type Object models grant full
  parent_id: null
- name: bc.models.crw
  note: Module bc Type Object models grant crw
  parent_id: null
