- ai.category:
    group_id: ai.models.readonly
    name: role.ai.models.ai.category.readonly
    note: 'Module: ai Type: models Object: ai.category grant: readonly'
- ai.category:
    group_id: ai.models.nodrop
    name: role.ai.models.ai.category.nodrop
    note: 'Module: ai Type: models Object: ai.category grant: nodrop'
- ai.category:
    group_id: ai.models.full
    name: role.ai.models.ai.category.full
    note: 'Module: ai Type: models Object: ai.category grant: full'
- ai.category:
    group_id: ai.models.crw
    name: role.ai.models.ai.category.crw
    note: 'Module: ai Type: models Object: ai.category grant: crw'
- ai.model:
    group_id: ai.models.readonly
    name: role.ai.models.ai.model.readonly
    note: 'Module: ai Type: models Object: ai.model grant: readonly'
- ai.model:
    group_id: ai.models.nodrop
    name: role.ai.models.ai.model.nodrop
    note: 'Module: ai Type: models Object: ai.model grant: nodrop'
- ai.model:
    group_id: ai.models.full
    name: role.ai.models.ai.model.full
    note: 'Module: ai Type: models Object: ai.model grant: full'
- ai.model:
    group_id: ai.models.crw
    name: role.ai.models.ai.model.crw
    note: 'Module: ai Type: models Object: ai.model grant: crw'
