- cols:
  - col: name
    seq: 0
  - col: element_id
    seq: 10
  - col: inactive
    seq: 20
  - col: note
    seq: 30
  model: wkf.routes
  vtype: element-plus/form
- cols:
  - col: name
    seq: 0
  - col: element_id
    seq: 10
  - col: inactive
    seq: 20
  - col: note
    seq: 30
  model: wkf.routes
  vtype: element-plus/form.modal
- cols:
  - col: name
    seq: 0
  - col: element_id
    seq: 10
  - col: inactive
    seq: 20
  model: wkf.routes
  vtype: element-plus/list
- cols:
  - col: name
    seq: 0
  - col: element_id
    seq: 10
  - col: inactive
    seq: 20
  model: wkf.routes
  vtype: element-plus/m2mlist
- cols:
  - col: name
    seq: 0
  - col: element_id
    seq: 10
  - col: inactive
    seq: 20
  model: wkf.routes
  vtype: element-plus/search
- cols:
  - col: name
    seq: 0
  - col: element_id
    seq: 10
  - col: inactive
    seq: 20
  model: wkf.routes
  vtype: element-plus/find
