- cols:
  - col: name
  - col: element_id
  - col: inactive
  - col: note
  model: wkf.routes
  vtype: element-plus/form
- cols:
  - col: name
  - col: element_id
  - col: inactive
  - col: note
  model: wkf.routes
  vtype: element-plus/form.modal
- cols:
  - col: name
  - col: element_id
  - col: inactive
  model: wkf.routes
  vtype: element-plus/list
- cols:
  - col: name
  - col: element_id
  - col: inactive
  model: wkf.routes
  vtype: element-plus/m2mlist
- cols:
  - col: name
  - col: element_id
  - col: inactive
  model: wkf.routes
  vtype: element-plus/search
- cols:
  - col: name
  - col: element_id
  - col: inactive
  model: wkf.routes
  vtype: element-plus/find
