- trm.inode.category:
    group_id: trm.models.readonly
    name: role.trm.models.trm.inode.category.readonly
    note: 'Module: trm Type: models Object: trm.inode.category grant: readonly'
- trm.inode.category:
    group_id: trm.models.nodrop
    name: role.trm.models.trm.inode.category.nodrop
    note: 'Module: trm Type: models Object: trm.inode.category grant: nodrop'
- trm.inode.category:
    group_id: trm.models.full
    name: role.trm.models.trm.inode.category.full
    note: 'Module: trm Type: models Object: trm.inode.category grant: full'
- trm.inode.category:
    group_id: trm.models.crw
    name: role.trm.models.trm.inode.category.crw
    note: 'Module: trm Type: models Object: trm.inode.category grant: crw'
- trm.vehicle.category:
    group_id: trm.models.readonly
    name: role.trm.models.trm.vehicle.category.readonly
    note: 'Module: trm Type: models Object: trm.vehicle.category grant: readonly'
- trm.vehicle.category:
    group_id: trm.models.nodrop
    name: role.trm.models.trm.vehicle.category.nodrop
    note: 'Module: trm Type: models Object: trm.vehicle.category grant: nodrop'
- trm.vehicle.category:
    group_id: trm.models.full
    name: role.trm.models.trm.vehicle.category.full
    note: 'Module: trm Type: models Object: trm.vehicle.category grant: full'
- trm.vehicle.category:
    group_id: trm.models.crw
    name: role.trm.models.trm.vehicle.category.crw
    note: 'Module: trm Type: models Object: trm.vehicle.category grant: crw'
- trm.inode:
    group_id: trm.models.readonly
    name: role.trm.models.trm.inode.readonly
    note: 'Module: trm Type: models Object: trm.inode grant: readonly'
- trm.inode:
    group_id: trm.models.nodrop
    name: role.trm.models.trm.inode.nodrop
    note: 'Module: trm Type: models Object: trm.inode grant: nodrop'
- trm.inode:
    group_id: trm.models.full
    name: role.trm.models.trm.inode.full
    note: 'Module: trm Type: models Object: trm.inode grant: full'
- trm.inode:
    group_id: trm.models.crw
    name: role.trm.models.trm.inode.crw
    note: 'Module: trm Type: models Object: trm.inode grant: crw'
- trm.vehicle:
    group_id: trm.models.readonly
    name: role.trm.models.trm.vehicle.readonly
    note: 'Module: trm Type: models Object: trm.vehicle grant: readonly'
- trm.vehicle:
    group_id: trm.models.nodrop
    name: role.trm.models.trm.vehicle.nodrop
    note: 'Module: trm Type: models Object: trm.vehicle grant: nodrop'
- trm.vehicle:
    group_id: trm.models.full
    name: role.trm.models.trm.vehicle.full
    note: 'Module: trm Type: models Object: trm.vehicle grant: full'
- trm.vehicle:
    group_id: trm.models.crw
    name: role.trm.models.trm.vehicle.crw
    note: 'Module: trm Type: models Object: trm.vehicle grant: crw'
- trm.unit.vehicle:
    group_id: trm.models.readonly
    name: role.trm.models.trm.unit.vehicle.readonly
    note: 'Module: trm Type: models Object: trm.unit.vehicle grant: readonly'
- trm.unit.vehicle:
    group_id: trm.models.nodrop
    name: role.trm.models.trm.unit.vehicle.nodrop
    note: 'Module: trm Type: models Object: trm.unit.vehicle grant: nodrop'
- trm.unit.vehicle:
    group_id: trm.models.full
    name: role.trm.models.trm.unit.vehicle.full
    note: 'Module: trm Type: models Object: trm.unit.vehicle grant: full'
- trm.unit.vehicle:
    group_id: trm.models.crw
    name: role.trm.models.trm.unit.vehicle.crw
    note: 'Module: trm Type: models Object: trm.unit.vehicle grant: crw'
