- name: trm.models.readonly
  note: Module trm Type Object models grant readonly
  parent_id: null
- name: trm.models.nodrop
  note: Module trm Type Object models grant nodrop
  parent_id: null
- name: trm.models.full
  note: Module trm Type Object models grant full
  parent_id: null
- name: trm.models.crw
  note: Module trm Type Object models grant crw
  parent_id: null
