- cols:
  - col: model_id
    seq: 0
  - col: sequence
    seq: 10
  - col: col
    seq: 20
  model: seq.model.column.values
  vtype: vuetify/form
- cols:
  - col: model_id
    seq: 0
  - col: sequence
    seq: 10
  - col: col
    seq: 20
  model: seq.model.column.values
  vtype: vuetify/form.modal
- cols:
  - col: model_id
    seq: 0
  - col: sequence
    seq: 10
  - col: col
    seq: 20
  model: seq.model.column.values
  vtype: vuetify/list
- cols:
  - col: model_id
    seq: 0
  - col: sequence
    seq: 10
  - col: col
    seq: 20
  model: seq.model.column.values
  vtype: vuetify/m2mlist
- cols:
  - col: model_id
    seq: 0
  - col: sequence
    seq: 10
  - col: col
    seq: 20
  model: seq.model.column.values
  vtype: vuetify/find
