- cols:
  - col: name
  - col: items
  - col: note
  model: srm.routes
  vtype: devextrme/form
- cols:
  - col: name
  - col: items
  - col: note
  model: srm.routes
  vtype: devextrme/form.modal
- cols:
  - col: name
  - col: items
  model: srm.routes
  vtype: devextrme/list
- cols:
  - col: name
  model: srm.routes
  vtype: devextrme/m2mlist
- cols:
  - col: name
  model: srm.routes
  vtype: devextrme/search
- cols:
  - col: name
  model: srm.routes
  vtype: devextrme/find
