- access:
    aread: true
  obj: ai.category
  obj_access_id: role.ai.models.ai.category.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: ai.category
  obj_access_id: role.ai.models.ai.category.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: ai.category
  obj_access_id: role.ai.models.ai.category.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: ai.category
  obj_access_id: role.ai.models.ai.category.crw
- access:
    aread: true
  obj: ai.model
  obj_access_id: role.ai.models.ai.model.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: ai.model
  obj_access_id: role.ai.models.ai.model.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: ai.model
  obj_access_id: role.ai.models.ai.model.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: ai.model
  obj_access_id: role.ai.models.ai.model.crw
