- name: oil2.models.readonly
  note: Module oil2 Type Object models grant readonly
- name: oil2.models.nodrop
  note: Module oil2 Type Object models grant nodrop
- name: oil2.models.full
  note: Module oil2 Type Object models grant full
- name: oil2.models.crw
  note: Module oil2 Type Object models grant crw
