- cols:
  - col: model_id
  - col: sequence
  - col: col
  model: seq.model.column.values
  vtype: devextrme/form
- cols:
  - col: model_id
  - col: sequence
  - col: col
  model: seq.model.column.values
  vtype: devextrme/form.modal
- cols:
  - col: model_id
  - col: sequence
  - col: col
  model: seq.model.column.values
  vtype: devextrme/list
- cols:
  - col: model_id
  - col: sequence
  - col: col
  model: seq.model.column.values
  vtype: devextrme/m2mlist
- cols:
  - col: model_id
  - col: sequence
  - col: col
  model: seq.model.column.values
  vtype: devextrme/search
- cols:
  - col: model_id
  - col: sequence
  - col: col
  model: seq.model.column.values
  vtype: devextrme/find
