from . import i18n_ru_md_okpd2
from . import i18n_ru_md_okved2
from . import i18n_ru_md_okof
from . import i18n_ru_md_okmto
from . import i18n_ru_md_okato
from . import i18n_ru_md_okso
from . import i18n_ru_md_okopf
from . import i18n_ru_md_okud
from . import i18n_ru_md_tnved
from . import i18n_ru_md_okei
from . import i18n_ru_md_okz