- name: le.models.readonly
  note: Module le Type Object models grant readonly
- name: le.models.nodrop
  note: Module le Type Object models grant nodrop
- name: le.models.full
  note: Module le Type Object models grant full
- name: le.models.crw
  note: Module le Type Object models grant crw
