- access:
    aread: true
  obj: cf.groups
  obj_access_id: role.cf.models.cf.groups.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: cf.groups
  obj_access_id: role.cf.models.cf.groups.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: cf.groups
  obj_access_id: role.cf.models.cf.groups.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: cf.groups
  obj_access_id: role.cf.models.cf.groups.crw
- access:
    aread: true
  obj: cf.tags
  obj_access_id: role.cf.models.cf.tags.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: cf.tags
  obj_access_id: role.cf.models.cf.tags.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: cf.tags
  obj_access_id: role.cf.models.cf.tags.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: cf.tags
  obj_access_id: role.cf.models.cf.tags.crw
- access:
    aread: true
  obj: cf.file.access.users
  obj_access_id: role.cf.models.cf.file.access.users.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: cf.file.access.users
  obj_access_id: role.cf.models.cf.file.access.users.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: cf.file.access.users
  obj_access_id: role.cf.models.cf.file.access.users.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: cf.file.access.users
  obj_access_id: role.cf.models.cf.file.access.users.crw
- access:
    aread: true
  obj: cf.file.access.groups
  obj_access_id: role.cf.models.cf.file.access.groups.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: cf.file.access.groups
  obj_access_id: role.cf.models.cf.file.access.groups.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: cf.file.access.groups
  obj_access_id: role.cf.models.cf.file.access.groups.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: cf.file.access.groups
  obj_access_id: role.cf.models.cf.file.access.groups.crw
- access:
    aread: true
  obj: cf.file.access.others
  obj_access_id: role.cf.models.cf.file.access.others.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: cf.file.access.others
  obj_access_id: role.cf.models.cf.file.access.others.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: cf.file.access.others
  obj_access_id: role.cf.models.cf.file.access.others.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: cf.file.access.others
  obj_access_id: role.cf.models.cf.file.access.others.crw
- access:
    aread: true
  obj: cf.files
  obj_access_id: role.cf.models.cf.files.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: cf.files
  obj_access_id: role.cf.models.cf.files.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: cf.files
  obj_access_id: role.cf.models.cf.files.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: cf.files
  obj_access_id: role.cf.models.cf.files.crw
- access:
    aread: true
  obj: cf.link.access.users
  obj_access_id: role.cf.models.cf.link.access.users.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: cf.link.access.users
  obj_access_id: role.cf.models.cf.link.access.users.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: cf.link.access.users
  obj_access_id: role.cf.models.cf.link.access.users.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: cf.link.access.users
  obj_access_id: role.cf.models.cf.link.access.users.crw
- access:
    aread: true
  obj: cf.link.access.groups
  obj_access_id: role.cf.models.cf.link.access.groups.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: cf.link.access.groups
  obj_access_id: role.cf.models.cf.link.access.groups.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: cf.link.access.groups
  obj_access_id: role.cf.models.cf.link.access.groups.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: cf.link.access.groups
  obj_access_id: role.cf.models.cf.link.access.groups.crw
- access:
    aread: true
  obj: cf.link.access.others
  obj_access_id: role.cf.models.cf.link.access.others.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: cf.link.access.others
  obj_access_id: role.cf.models.cf.link.access.others.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: cf.link.access.others
  obj_access_id: role.cf.models.cf.link.access.others.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: cf.link.access.others
  obj_access_id: role.cf.models.cf.link.access.others.crw
- access:
    aread: true
  obj: cf.links
  obj_access_id: role.cf.models.cf.links.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: cf.links
  obj_access_id: role.cf.models.cf.links.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: cf.links
  obj_access_id: role.cf.models.cf.links.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: cf.links
  obj_access_id: role.cf.models.cf.links.crw
- access:
    aread: true
  obj: cf.folder.access.users
  obj_access_id: role.cf.models.cf.folder.access.users.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: cf.folder.access.users
  obj_access_id: role.cf.models.cf.folder.access.users.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: cf.folder.access.users
  obj_access_id: role.cf.models.cf.folder.access.users.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: cf.folder.access.users
  obj_access_id: role.cf.models.cf.folder.access.users.crw
- access:
    aread: true
  obj: cf.folder.access.groups
  obj_access_id: role.cf.models.cf.folder.access.groups.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: cf.folder.access.groups
  obj_access_id: role.cf.models.cf.folder.access.groups.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: cf.folder.access.groups
  obj_access_id: role.cf.models.cf.folder.access.groups.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: cf.folder.access.groups
  obj_access_id: role.cf.models.cf.folder.access.groups.crw
- access:
    aread: true
  obj: cf.folder.access.others
  obj_access_id: role.cf.models.cf.folder.access.others.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: cf.folder.access.others
  obj_access_id: role.cf.models.cf.folder.access.others.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: cf.folder.access.others
  obj_access_id: role.cf.models.cf.folder.access.others.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: cf.folder.access.others
  obj_access_id: role.cf.models.cf.folder.access.others.crw
- access:
    aread: true
  obj: cf.folders
  obj_access_id: role.cf.models.cf.folders.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: cf.folders
  obj_access_id: role.cf.models.cf.folders.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: cf.folders
  obj_access_id: role.cf.models.cf.folders.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: cf.folders
  obj_access_id: role.cf.models.cf.folders.crw
