- cols:
  - name
  - items
  - note
  framework: elemnt-plus
  model: srm.routes
  vtype: form
- cols:
  - name
  - items
  - note
  framework: elemnt-plus
  model: srm.routes
  vtype: form.modal
- cols:
  - name
  - items
  framework: elemnt-plus
  model: srm.routes
  vtype: list
- cols:
  - name
  framework: elemnt-plus
  model: srm.routes
  vtype: m2mlist
- cols:
  - name
  framework: elemnt-plus
  model: srm.routes
  vtype: search
- cols:
  - name
  framework: elemnt-plus
  model: srm.routes
  vtype: find
