- name: ewm.models.readonly
  note: Module ewm Type Object models grant readonly
- name: ewm.models.nodrop
  note: Module ewm Type Object models grant nodrop
- name: ewm.models.full
  note: Module ewm Type Object models grant full
- name: ewm.models.crw
  note: Module ewm Type Object models grant crw
