- group_id: ewm.models.readonly
  name: role.ewm.models.ewm.warehouse.readonly
  note: 'Module: ewm Type: models Object: ewm.warehouse grant: readonly'
- group_id: ewm.models.nodrop
  name: role.ewm.models.ewm.warehouse.nodrop
  note: 'Module: ewm Type: models Object: ewm.warehouse grant: nodrop'
- group_id: ewm.models.full
  name: role.ewm.models.ewm.warehouse.full
  note: 'Module: ewm Type: models Object: ewm.warehouse grant: full'
- group_id: ewm.models.crw
  name: role.ewm.models.ewm.warehouse.crw
  note: 'Module: ewm Type: models Object: ewm.warehouse grant: crw'
- group_id: ewm.models.readonly
  name: role.ewm.models.st.company.product.quantites.readonly
  note: 'Module: ewm Type: models Object: st.company.product.quantites grant: readonly'
- group_id: ewm.models.nodrop
  name: role.ewm.models.st.company.product.quantites.nodrop
  note: 'Module: ewm Type: models Object: st.company.product.quantites grant: nodrop'
- group_id: ewm.models.full
  name: role.ewm.models.st.company.product.quantites.full
  note: 'Module: ewm Type: models Object: st.company.product.quantites grant: full'
- group_id: ewm.models.crw
  name: role.ewm.models.st.company.product.quantites.crw
  note: 'Module: ewm Type: models Object: st.company.product.quantites grant: crw'
- group_id: ewm.models.readonly
  name: role.ewm.models.st.stock.product.quantites.readonly
  note: 'Module: ewm Type: models Object: st.stock.product.quantites grant: readonly'
- group_id: ewm.models.nodrop
  name: role.ewm.models.st.stock.product.quantites.nodrop
  note: 'Module: ewm Type: models Object: st.stock.product.quantites grant: nodrop'
- group_id: ewm.models.full
  name: role.ewm.models.st.stock.product.quantites.full
  note: 'Module: ewm Type: models Object: st.stock.product.quantites grant: full'
- group_id: ewm.models.crw
  name: role.ewm.models.st.stock.product.quantites.crw
  note: 'Module: ewm Type: models Object: st.stock.product.quantites grant: crw'
- group_id: ewm.models.readonly
  name: role.ewm.models.md.ewm.product.readonly
  note: 'Module: ewm Type: models Object: md.ewm.product grant: readonly'
- group_id: ewm.models.nodrop
  name: role.ewm.models.md.ewm.product.nodrop
  note: 'Module: ewm Type: models Object: md.ewm.product grant: nodrop'
- group_id: ewm.models.full
  name: role.ewm.models.md.ewm.product.full
  note: 'Module: ewm Type: models Object: md.ewm.product grant: full'
- group_id: ewm.models.crw
  name: role.ewm.models.md.ewm.product.crw
  note: 'Module: ewm Type: models Object: md.ewm.product grant: crw'
