- cols:
  - col: name
    seq: 0
  - col: items
    seq: 10
  - col: note
    seq: 20
  model: srm.routes
  vtype: element-plus/form
- cols:
  - col: name
    seq: 0
  - col: items
    seq: 10
  - col: note
    seq: 20
  model: srm.routes
  vtype: element-plus/form.modal
- cols:
  - col: name
    seq: 0
  - col: items
    seq: 10
  model: srm.routes
  vtype: element-plus/list
- cols:
  - col: name
    seq: 0
  model: srm.routes
  vtype: element-plus/m2mlist
- cols:
  - col: name
    seq: 0
  model: srm.routes
  vtype: element-plus/search
- cols:
  - col: name
    seq: 0
  model: srm.routes
  vtype: element-plus/find
