- cols:
  - col: name
  - col: items
  - col: note
  model: srm.routes
  vtype: element-plus/form
- cols:
  - col: name
  - col: items
  - col: note
  model: srm.routes
  vtype: element-plus/form.modal
- cols:
  - col: name
  - col: items
  model: srm.routes
  vtype: element-plus/list
- cols:
  - col: name
  model: srm.routes
  vtype: element-plus/m2mlist
- cols:
  - col: name
  model: srm.routes
  vtype: element-plus/search
- cols:
  - col: name
  model: srm.routes
  vtype: element-plus/find
