- cols:
  - col: name
  - col: element_id
  - col: inactive
  - col: note
  model: wkf.routes
  vtype: vuetify/form
- cols:
  - col: name
  - col: element_id
  - col: inactive
  - col: note
  model: wkf.routes
  vtype: vuetify/form.modal
- cols:
  - col: name
  - col: element_id
  - col: inactive
  model: wkf.routes
  vtype: vuetify/list
- cols:
  - col: name
  - col: element_id
  - col: inactive
  model: wkf.routes
  vtype: vuetify/m2mlist
- cols:
  - col: name
  - col: element_id
  - col: inactive
  model: wkf.routes
  vtype: vuetify/search
- cols:
  - col: name
  - col: element_id
  - col: inactive
  model: wkf.routes
  vtype: vuetify/find
