- name: purchase.models.readonly
  note: Module purchase Type Object models grant readonly
  parent_id: null
- name: purchase.models.nodrop
  note: Module purchase Type Object models grant nodrop
  parent_id: null
- name: purchase.models.full
  note: Module purchase Type Object models grant full
  parent_id: null
- name: purchase.models.crw
  note: Module purchase Type Object models grant crw
  parent_id: null
