- access:
    aread: true
  obj: common.sequencies
  obj_access_id: role.common.models.common.sequencies.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: common.sequencies
  obj_access_id: role.common.models.common.sequencies.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: common.sequencies
  obj_access_id: role.common.models.common.sequencies.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: common.sequencies
  obj_access_id: role.common.models.common.sequencies.crw
- access:
    aread: true
  obj: common.sequence.access
  obj_access_id: role.common.models.common.sequence.access.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: common.sequence.access
  obj_access_id: role.common.models.common.sequence.access.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: common.sequence.access
  obj_access_id: role.common.models.common.sequence.access.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: common.sequence.access
  obj_access_id: role.common.models.common.sequence.access.crw
- access:
    aread: true
  obj: common.sequence.conditions
  obj_access_id: role.common.models.common.sequence.conditions.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: common.sequence.conditions
  obj_access_id: role.common.models.common.sequence.conditions.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: common.sequence.conditions
  obj_access_id: role.common.models.common.sequence.conditions.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: common.sequence.conditions
  obj_access_id: role.common.models.common.sequence.conditions.crw
- access:
    aread: true
  obj: common.sequence.schemas
  obj_access_id: role.common.models.common.sequence.schemas.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: common.sequence.schemas
  obj_access_id: role.common.models.common.sequence.schemas.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: common.sequence.schemas
  obj_access_id: role.common.models.common.sequence.schemas.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: common.sequence.schemas
  obj_access_id: role.common.models.common.sequence.schemas.crw
- access:
    aread: true
  obj: seq.areas
  obj_access_id: role.common.models.seq.areas.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: seq.areas
  obj_access_id: role.common.models.seq.areas.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: seq.areas
  obj_access_id: role.common.models.seq.areas.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: seq.areas
  obj_access_id: role.common.models.seq.areas.crw
- access:
    aread: true
  obj: seq.segments
  obj_access_id: role.common.models.seq.segments.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: seq.segments
  obj_access_id: role.common.models.seq.segments.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: seq.segments
  obj_access_id: role.common.models.seq.segments.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: seq.segments
  obj_access_id: role.common.models.seq.segments.crw
- access:
    aread: true
  obj: seq.access
  obj_access_id: role.common.models.seq.access.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: seq.access
  obj_access_id: role.common.models.seq.access.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: seq.access
  obj_access_id: role.common.models.seq.access.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: seq.access
  obj_access_id: role.common.models.seq.access.crw
- access:
    aread: true
  obj: seq.models
  obj_access_id: role.common.models.seq.models.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: seq.models
  obj_access_id: role.common.models.seq.models.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: seq.models
  obj_access_id: role.common.models.seq.models.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: seq.models
  obj_access_id: role.common.models.seq.models.crw
- access:
    aread: true
  obj: seq.model.columns
  obj_access_id: role.common.models.seq.model.columns.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: seq.model.columns
  obj_access_id: role.common.models.seq.model.columns.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: seq.model.columns
  obj_access_id: role.common.models.seq.model.columns.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: seq.model.columns
  obj_access_id: role.common.models.seq.model.columns.crw
- access:
    aread: true
  obj: seq.model.column.values
  obj_access_id: role.common.models.seq.model.column.values.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: seq.model.column.values
  obj_access_id: role.common.models.seq.model.column.values.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: seq.model.column.values
  obj_access_id: role.common.models.seq.model.column.values.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: seq.model.column.values
  obj_access_id: role.common.models.seq.model.column.values.crw
- access:
    aread: true
  obj: seq.conditions
  obj_access_id: role.common.models.seq.conditions.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: seq.conditions
  obj_access_id: role.common.models.seq.conditions.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: seq.conditions
  obj_access_id: role.common.models.seq.conditions.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: seq.conditions
  obj_access_id: role.common.models.seq.conditions.crw
- access:
    aread: true
  obj: seq.access.schemas
  obj_access_id: role.common.models.seq.access.schemas.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: seq.access.schemas
  obj_access_id: role.common.models.seq.access.schemas.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: seq.access.schemas
  obj_access_id: role.common.models.seq.access.schemas.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: seq.access.schemas
  obj_access_id: role.common.models.seq.access.schemas.crw
- access:
    aread: true
  obj: seq.access.schema.items
  obj_access_id: role.common.models.seq.access.schema.items.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: seq.access.schema.items
  obj_access_id: role.common.models.seq.access.schema.items.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: seq.access.schema.items
  obj_access_id: role.common.models.seq.access.schema.items.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: seq.access.schema.items
  obj_access_id: role.common.models.seq.access.schema.items.crw
