- name: ml.models.readonly
  note: Module ml Type Object models grant readonly
- name: ml.models.nodrop
  note: Module ml Type Object models grant nodrop
- name: ml.models.full
  note: Module ml Type Object models grant full
- name: ml.models.crw
  note: Module ml Type Object models grant crw
