- cols:
  - col: name
  - col: element_id
  - col: inactive
  - col: note
  model: wkf.routes
  vtype: devextrme/form
- cols:
  - col: name
  - col: element_id
  - col: inactive
  - col: note
  model: wkf.routes
  vtype: devextrme/form.modal
- cols:
  - col: name
  - col: element_id
  - col: inactive
  model: wkf.routes
  vtype: devextrme/list
- cols:
  - col: name
  - col: element_id
  - col: inactive
  model: wkf.routes
  vtype: devextrme/m2mlist
- cols:
  - col: name
  - col: element_id
  - col: inactive
  model: wkf.routes
  vtype: devextrme/search
- cols:
  - col: name
  - col: element_id
  - col: inactive
  model: wkf.routes
  vtype: devextrme/find
