- cols:
  - name
  - element_id
  - inactive
  - note
  framework: devextrme
  model: wkf.routes
  vtype: form
- cols:
  - name
  - element_id
  - inactive
  - note
  framework: devextrme
  model: wkf.routes
  vtype: form.modal
- cols:
  - name
  - element_id
  - inactive
  framework: devextrme
  model: wkf.routes
  vtype: list
- cols:
  - name
  - element_id
  - inactive
  framework: devextrme
  model: wkf.routes
  vtype: m2mlist
- cols:
  - name
  - element_id
  - inactive
  framework: devextrme
  model: wkf.routes
  vtype: search
- cols:
  - name
  - element_id
  - inactive
  framework: devextrme
  model: wkf.routes
  vtype: find
