- name: ehs.models.readonly
  note: Module ehs Type Object models grant readonly
- name: ehs.models.nodrop
  note: Module ehs Type Object models grant nodrop
- name: ehs.models.full
  note: Module ehs Type Object models grant full
- name: ehs.models.crw
  note: Module ehs Type Object models grant crw
