- cols:
  - col: name
  - col: items
  - col: note
  model: srm.routes
  vtype: vuetify/form
- cols:
  - col: name
  - col: items
  - col: note
  model: srm.routes
  vtype: vuetify/form.modal
- cols:
  - col: name
  - col: items
  model: srm.routes
  vtype: vuetify/list
- cols:
  - col: name
  model: srm.routes
  vtype: vuetify/m2mlist
- cols:
  - col: name
  model: srm.routes
  vtype: vuetify/search
- cols:
  - col: name
  model: srm.routes
  vtype: vuetify/find
