- name: oil.models.readonly
  note: Module oil Type Object models grant readonly
  parent_id: null
- name: oil.models.nodrop
  note: Module oil Type Object models grant nodrop
  parent_id: null
- name: oil.models.full
  note: Module oil Type Object models grant full
  parent_id: null
- name: oil.models.crw
  note: Module oil Type Object models grant crw
  parent_id: null
