- group_id: cf.models.readonly
  name: role.cf.models.cf.groups.readonly
  note: 'Module: cf Type: models Object: cf.groups grant: readonly'
- group_id: cf.models.nodrop
  name: role.cf.models.cf.groups.nodrop
  note: 'Module: cf Type: models Object: cf.groups grant: nodrop'
- group_id: cf.models.full
  name: role.cf.models.cf.groups.full
  note: 'Module: cf Type: models Object: cf.groups grant: full'
- group_id: cf.models.crw
  name: role.cf.models.cf.groups.crw
  note: 'Module: cf Type: models Object: cf.groups grant: crw'
- group_id: cf.models.readonly
  name: role.cf.models.cf.tags.readonly
  note: 'Module: cf Type: models Object: cf.tags grant: readonly'
- group_id: cf.models.nodrop
  name: role.cf.models.cf.tags.nodrop
  note: 'Module: cf Type: models Object: cf.tags grant: nodrop'
- group_id: cf.models.full
  name: role.cf.models.cf.tags.full
  note: 'Module: cf Type: models Object: cf.tags grant: full'
- group_id: cf.models.crw
  name: role.cf.models.cf.tags.crw
  note: 'Module: cf Type: models Object: cf.tags grant: crw'
- group_id: cf.models.readonly
  name: role.cf.models.cf.file.access.users.readonly
  note: 'Module: cf Type: models Object: cf.file.access.users grant: readonly'
- group_id: cf.models.nodrop
  name: role.cf.models.cf.file.access.users.nodrop
  note: 'Module: cf Type: models Object: cf.file.access.users grant: nodrop'
- group_id: cf.models.full
  name: role.cf.models.cf.file.access.users.full
  note: 'Module: cf Type: models Object: cf.file.access.users grant: full'
- group_id: cf.models.crw
  name: role.cf.models.cf.file.access.users.crw
  note: 'Module: cf Type: models Object: cf.file.access.users grant: crw'
- group_id: cf.models.readonly
  name: role.cf.models.cf.file.access.groups.readonly
  note: 'Module: cf Type: models Object: cf.file.access.groups grant: readonly'
- group_id: cf.models.nodrop
  name: role.cf.models.cf.file.access.groups.nodrop
  note: 'Module: cf Type: models Object: cf.file.access.groups grant: nodrop'
- group_id: cf.models.full
  name: role.cf.models.cf.file.access.groups.full
  note: 'Module: cf Type: models Object: cf.file.access.groups grant: full'
- group_id: cf.models.crw
  name: role.cf.models.cf.file.access.groups.crw
  note: 'Module: cf Type: models Object: cf.file.access.groups grant: crw'
- group_id: cf.models.readonly
  name: role.cf.models.cf.file.access.others.readonly
  note: 'Module: cf Type: models Object: cf.file.access.others grant: readonly'
- group_id: cf.models.nodrop
  name: role.cf.models.cf.file.access.others.nodrop
  note: 'Module: cf Type: models Object: cf.file.access.others grant: nodrop'
- group_id: cf.models.full
  name: role.cf.models.cf.file.access.others.full
  note: 'Module: cf Type: models Object: cf.file.access.others grant: full'
- group_id: cf.models.crw
  name: role.cf.models.cf.file.access.others.crw
  note: 'Module: cf Type: models Object: cf.file.access.others grant: crw'
- group_id: cf.models.readonly
  name: role.cf.models.cf.files.readonly
  note: 'Module: cf Type: models Object: cf.files grant: readonly'
- group_id: cf.models.nodrop
  name: role.cf.models.cf.files.nodrop
  note: 'Module: cf Type: models Object: cf.files grant: nodrop'
- group_id: cf.models.full
  name: role.cf.models.cf.files.full
  note: 'Module: cf Type: models Object: cf.files grant: full'
- group_id: cf.models.crw
  name: role.cf.models.cf.files.crw
  note: 'Module: cf Type: models Object: cf.files grant: crw'
- group_id: cf.models.readonly
  name: role.cf.models.cf.link.access.users.readonly
  note: 'Module: cf Type: models Object: cf.link.access.users grant: readonly'
- group_id: cf.models.nodrop
  name: role.cf.models.cf.link.access.users.nodrop
  note: 'Module: cf Type: models Object: cf.link.access.users grant: nodrop'
- group_id: cf.models.full
  name: role.cf.models.cf.link.access.users.full
  note: 'Module: cf Type: models Object: cf.link.access.users grant: full'
- group_id: cf.models.crw
  name: role.cf.models.cf.link.access.users.crw
  note: 'Module: cf Type: models Object: cf.link.access.users grant: crw'
- group_id: cf.models.readonly
  name: role.cf.models.cf.link.access.groups.readonly
  note: 'Module: cf Type: models Object: cf.link.access.groups grant: readonly'
- group_id: cf.models.nodrop
  name: role.cf.models.cf.link.access.groups.nodrop
  note: 'Module: cf Type: models Object: cf.link.access.groups grant: nodrop'
- group_id: cf.models.full
  name: role.cf.models.cf.link.access.groups.full
  note: 'Module: cf Type: models Object: cf.link.access.groups grant: full'
- group_id: cf.models.crw
  name: role.cf.models.cf.link.access.groups.crw
  note: 'Module: cf Type: models Object: cf.link.access.groups grant: crw'
- group_id: cf.models.readonly
  name: role.cf.models.cf.link.access.others.readonly
  note: 'Module: cf Type: models Object: cf.link.access.others grant: readonly'
- group_id: cf.models.nodrop
  name: role.cf.models.cf.link.access.others.nodrop
  note: 'Module: cf Type: models Object: cf.link.access.others grant: nodrop'
- group_id: cf.models.full
  name: role.cf.models.cf.link.access.others.full
  note: 'Module: cf Type: models Object: cf.link.access.others grant: full'
- group_id: cf.models.crw
  name: role.cf.models.cf.link.access.others.crw
  note: 'Module: cf Type: models Object: cf.link.access.others grant: crw'
- group_id: cf.models.readonly
  name: role.cf.models.cf.links.readonly
  note: 'Module: cf Type: models Object: cf.links grant: readonly'
- group_id: cf.models.nodrop
  name: role.cf.models.cf.links.nodrop
  note: 'Module: cf Type: models Object: cf.links grant: nodrop'
- group_id: cf.models.full
  name: role.cf.models.cf.links.full
  note: 'Module: cf Type: models Object: cf.links grant: full'
- group_id: cf.models.crw
  name: role.cf.models.cf.links.crw
  note: 'Module: cf Type: models Object: cf.links grant: crw'
- group_id: cf.models.readonly
  name: role.cf.models.cf.folder.access.users.readonly
  note: 'Module: cf Type: models Object: cf.folder.access.users grant: readonly'
- group_id: cf.models.nodrop
  name: role.cf.models.cf.folder.access.users.nodrop
  note: 'Module: cf Type: models Object: cf.folder.access.users grant: nodrop'
- group_id: cf.models.full
  name: role.cf.models.cf.folder.access.users.full
  note: 'Module: cf Type: models Object: cf.folder.access.users grant: full'
- group_id: cf.models.crw
  name: role.cf.models.cf.folder.access.users.crw
  note: 'Module: cf Type: models Object: cf.folder.access.users grant: crw'
- group_id: cf.models.readonly
  name: role.cf.models.cf.folder.access.groups.readonly
  note: 'Module: cf Type: models Object: cf.folder.access.groups grant: readonly'
- group_id: cf.models.nodrop
  name: role.cf.models.cf.folder.access.groups.nodrop
  note: 'Module: cf Type: models Object: cf.folder.access.groups grant: nodrop'
- group_id: cf.models.full
  name: role.cf.models.cf.folder.access.groups.full
  note: 'Module: cf Type: models Object: cf.folder.access.groups grant: full'
- group_id: cf.models.crw
  name: role.cf.models.cf.folder.access.groups.crw
  note: 'Module: cf Type: models Object: cf.folder.access.groups grant: crw'
- group_id: cf.models.readonly
  name: role.cf.models.cf.folder.access.others.readonly
  note: 'Module: cf Type: models Object: cf.folder.access.others grant: readonly'
- group_id: cf.models.nodrop
  name: role.cf.models.cf.folder.access.others.nodrop
  note: 'Module: cf Type: models Object: cf.folder.access.others grant: nodrop'
- group_id: cf.models.full
  name: role.cf.models.cf.folder.access.others.full
  note: 'Module: cf Type: models Object: cf.folder.access.others grant: full'
- group_id: cf.models.crw
  name: role.cf.models.cf.folder.access.others.crw
  note: 'Module: cf Type: models Object: cf.folder.access.others grant: crw'
- group_id: cf.models.readonly
  name: role.cf.models.cf.folders.readonly
  note: 'Module: cf Type: models Object: cf.folders grant: readonly'
- group_id: cf.models.nodrop
  name: role.cf.models.cf.folders.nodrop
  note: 'Module: cf Type: models Object: cf.folders grant: nodrop'
- group_id: cf.models.full
  name: role.cf.models.cf.folders.full
  note: 'Module: cf Type: models Object: cf.folders grant: full'
- group_id: cf.models.crw
  name: role.cf.models.cf.folders.crw
  note: 'Module: cf Type: models Object: cf.folders grant: crw'
