- name: md.models.readonly
  note: Module md Type Object models grant readonly
- name: md.models.nodrop
  note: Module md Type Object models grant nodrop
- name: md.models.full
  note: Module md Type Object models grant full
- name: md.models.crw
  note: Module md Type Object models grant crw
