- name: md.models.readonly
  note: Module md Type Object models grant readonly
  parent_id: null
- name: md.models.nodrop
  note: Module md Type Object models grant nodrop
  parent_id: null
- name: md.models.full
  note: Module md Type Object models grant full
  parent_id: null
- name: md.models.crw
  note: Module md Type Object models grant crw
  parent_id: null
