from . import fa_accounts_type
from . import fa_accounts_tag
from . import fa_accounts
from . import fa_accounts_group
from . import fa_accounts_journal
from . import fa_accounts_tax_group
from . import fa_accounts_tax
from . import fa_accounts_reconcile_model
from . import fa_account_template
from . import fa_chart_template
from . import fa_tax_template
from . import fa_fiscal_position_template
from . import fa_fiscal_position_tax_template
from . import fa_fiscal_position_account_template
from . import fa_reconcile_model_template
from . import fa_accounts_payment_method