- name: crm.models.readonly
  note: Module crm Type Object models grant readonly
- name: crm.models.nodrop
  note: Module crm Type Object models grant nodrop
- name: crm.models.full
  note: Module crm Type Object models grant full
- name: crm.models.crw
  note: Module crm Type Object models grant crw
