- access_id: role.wkf.models.wkf.locations.readonly
  aread: true
  model: wkf.locations
- access_id: role.wkf.models.wkf.locations.nodrop
  acreate: true
  aread: true
  awrite: true
  model: wkf.locations
- access_id: role.wkf.models.wkf.locations.full
  acreate: true
  aexecute: true
  aread: true
  aunlink: true
  awrite: true
  model: wkf.locations
- access_id: role.wkf.models.wkf.locations.crw
  acreate: true
  aexecute: true
  aread: true
  awrite: true
  model: wkf.locations
- access_id: role.wkf.models.wkf.workplice.categories.readonly
  aread: true
  model: wkf.workplice.categories
- access_id: role.wkf.models.wkf.workplice.categories.nodrop
  acreate: true
  aread: true
  awrite: true
  model: wkf.workplice.categories
- access_id: role.wkf.models.wkf.workplice.categories.full
  acreate: true
  aexecute: true
  aread: true
  aunlink: true
  awrite: true
  model: wkf.workplice.categories
- access_id: role.wkf.models.wkf.workplice.categories.crw
  acreate: true
  aexecute: true
  aread: true
  awrite: true
  model: wkf.workplice.categories
- access_id: role.wkf.models.wkf.workplace.readonly
  aread: true
  model: wkf.workplace
- access_id: role.wkf.models.wkf.workplace.nodrop
  acreate: true
  aread: true
  awrite: true
  model: wkf.workplace
- access_id: role.wkf.models.wkf.workplace.full
  acreate: true
  aexecute: true
  aread: true
  aunlink: true
  awrite: true
  model: wkf.workplace
- access_id: role.wkf.models.wkf.workplace.crw
  acreate: true
  aexecute: true
  aread: true
  awrite: true
  model: wkf.workplace
- access_id: role.wkf.models.wkf.element.categories.readonly
  aread: true
  model: wkf.element.categories
- access_id: role.wkf.models.wkf.element.categories.nodrop
  acreate: true
  aread: true
  awrite: true
  model: wkf.element.categories
- access_id: role.wkf.models.wkf.element.categories.full
  acreate: true
  aexecute: true
  aread: true
  aunlink: true
  awrite: true
  model: wkf.element.categories
- access_id: role.wkf.models.wkf.element.categories.crw
  acreate: true
  aexecute: true
  aread: true
  awrite: true
  model: wkf.element.categories
- access_id: role.wkf.models.wkf.elements.readonly
  aread: true
  model: wkf.elements
- access_id: role.wkf.models.wkf.elements.nodrop
  acreate: true
  aread: true
  awrite: true
  model: wkf.elements
- access_id: role.wkf.models.wkf.elements.full
  acreate: true
  aexecute: true
  aread: true
  aunlink: true
  awrite: true
  model: wkf.elements
- access_id: role.wkf.models.wkf.elements.crw
  acreate: true
  aexecute: true
  aread: true
  awrite: true
  model: wkf.elements
- access_id: role.wkf.models.wkf.routes.readonly
  aread: true
  model: wkf.routes
- access_id: role.wkf.models.wkf.routes.nodrop
  acreate: true
  aread: true
  awrite: true
  model: wkf.routes
- access_id: role.wkf.models.wkf.routes.full
  acreate: true
  aexecute: true
  aread: true
  aunlink: true
  awrite: true
  model: wkf.routes
- access_id: role.wkf.models.wkf.routes.crw
  acreate: true
  aexecute: true
  aread: true
  awrite: true
  model: wkf.routes
- access_id: role.wkf.models.wkf.jobs.readonly
  aread: true
  model: wkf.jobs
- access_id: role.wkf.models.wkf.jobs.nodrop
  acreate: true
  aread: true
  awrite: true
  model: wkf.jobs
- access_id: role.wkf.models.wkf.jobs.full
  acreate: true
  aexecute: true
  aread: true
  aunlink: true
  awrite: true
  model: wkf.jobs
- access_id: role.wkf.models.wkf.jobs.crw
  acreate: true
  aexecute: true
  aread: true
  awrite: true
  model: wkf.jobs
- access_id: role.wkf.models.wkf.job.history.readonly
  aread: true
  model: wkf.job.history
- access_id: role.wkf.models.wkf.job.history.nodrop
  acreate: true
  aread: true
  awrite: true
  model: wkf.job.history
- access_id: role.wkf.models.wkf.job.history.full
  acreate: true
  aexecute: true
  aread: true
  aunlink: true
  awrite: true
  model: wkf.job.history
- access_id: role.wkf.models.wkf.job.history.crw
  acreate: true
  aexecute: true
  aread: true
  awrite: true
  model: wkf.job.history
