- group_id: stock.models.readonly
  name: role.stock.models.st.location.readonly
  note: 'Module: stock Type: models Object: st.location grant: readonly'
- group_id: stock.models.nodrop
  name: role.stock.models.st.location.nodrop
  note: 'Module: stock Type: models Object: st.location grant: nodrop'
- group_id: stock.models.full
  name: role.stock.models.st.location.full
  note: 'Module: stock Type: models Object: st.location grant: full'
- group_id: stock.models.crw
  name: role.stock.models.st.location.crw
  note: 'Module: stock Type: models Object: st.location grant: crw'
- group_id: stock.models.readonly
  name: role.stock.models.st.stock.readonly
  note: 'Module: stock Type: models Object: st.stock grant: readonly'
- group_id: stock.models.nodrop
  name: role.stock.models.st.stock.nodrop
  note: 'Module: stock Type: models Object: st.stock grant: nodrop'
- group_id: stock.models.full
  name: role.stock.models.st.stock.full
  note: 'Module: stock Type: models Object: st.stock grant: full'
- group_id: stock.models.crw
  name: role.stock.models.st.stock.crw
  note: 'Module: stock Type: models Object: st.stock grant: crw'
- group_id: stock.models.readonly
  name: role.stock.models.st.company.product.quantites.readonly
  note: 'Module: stock Type: models Object: st.company.product.quantites grant: readonly'
- group_id: stock.models.nodrop
  name: role.stock.models.st.company.product.quantites.nodrop
  note: 'Module: stock Type: models Object: st.company.product.quantites grant: nodrop'
- group_id: stock.models.full
  name: role.stock.models.st.company.product.quantites.full
  note: 'Module: stock Type: models Object: st.company.product.quantites grant: full'
- group_id: stock.models.crw
  name: role.stock.models.st.company.product.quantites.crw
  note: 'Module: stock Type: models Object: st.company.product.quantites grant: crw'
- group_id: stock.models.readonly
  name: role.stock.models.st.stock.product.quantites.readonly
  note: 'Module: stock Type: models Object: st.stock.product.quantites grant: readonly'
- group_id: stock.models.nodrop
  name: role.stock.models.st.stock.product.quantites.nodrop
  note: 'Module: stock Type: models Object: st.stock.product.quantites grant: nodrop'
- group_id: stock.models.full
  name: role.stock.models.st.stock.product.quantites.full
  note: 'Module: stock Type: models Object: st.stock.product.quantites grant: full'
- group_id: stock.models.crw
  name: role.stock.models.st.stock.product.quantites.crw
  note: 'Module: stock Type: models Object: st.stock.product.quantites grant: crw'
- group_id: stock.models.readonly
  name: role.stock.models.md.stock.product.readonly
  note: 'Module: stock Type: models Object: md.stock.product grant: readonly'
- group_id: stock.models.nodrop
  name: role.stock.models.md.stock.product.nodrop
  note: 'Module: stock Type: models Object: md.stock.product grant: nodrop'
- group_id: stock.models.full
  name: role.stock.models.md.stock.product.full
  note: 'Module: stock Type: models Object: md.stock.product grant: full'
- group_id: stock.models.crw
  name: role.stock.models.md.stock.product.crw
  note: 'Module: stock Type: models Object: md.stock.product grant: crw'
