- access:
    aread: true
  obj: devel.area.messages
  obj_access_id: role.devel.models.devel.area.messages.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: devel.area.messages
  obj_access_id: role.devel.models.devel.area.messages.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: devel.area.messages
  obj_access_id: role.devel.models.devel.area.messages.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: devel.area.messages
  obj_access_id: role.devel.models.devel.area.messages.crw
- access:
    aread: true
  obj: devel.messages
  obj_access_id: role.devel.models.devel.messages.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: devel.messages
  obj_access_id: role.devel.models.devel.messages.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: devel.messages
  obj_access_id: role.devel.models.devel.messages.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: devel.messages
  obj_access_id: role.devel.models.devel.messages.crw
- access:
    aread: true
  obj: devel.web.frameworks
  obj_access_id: role.devel.models.devel.web.frameworks.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: devel.web.frameworks
  obj_access_id: role.devel.models.devel.web.frameworks.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: devel.web.frameworks
  obj_access_id: role.devel.models.devel.web.frameworks.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: devel.web.frameworks
  obj_access_id: role.devel.models.devel.web.frameworks.crw
- access:
    aread: true
  obj: devel.ui.view.model.types
  obj_access_id: role.devel.models.devel.ui.view.model.types.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: devel.ui.view.model.types
  obj_access_id: role.devel.models.devel.ui.view.model.types.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: devel.ui.view.model.types
  obj_access_id: role.devel.models.devel.ui.view.model.types.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: devel.ui.view.model.types
  obj_access_id: role.devel.models.devel.ui.view.model.types.crw
- access:
    aread: true
  obj: devel.ui.model.views
  obj_access_id: role.devel.models.devel.ui.model.views.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: devel.ui.model.views
  obj_access_id: role.devel.models.devel.ui.model.views.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: devel.ui.model.views
  obj_access_id: role.devel.models.devel.ui.model.views.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: devel.ui.model.views
  obj_access_id: role.devel.models.devel.ui.model.views.crw
- access:
    aread: true
  obj: devel.ui.model.view.columns
  obj_access_id: role.devel.models.devel.ui.model.view.columns.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: devel.ui.model.view.columns
  obj_access_id: role.devel.models.devel.ui.model.view.columns.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: devel.ui.model.view.columns
  obj_access_id: role.devel.models.devel.ui.model.view.columns.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: devel.ui.model.view.columns
  obj_access_id: role.devel.models.devel.ui.model.view.columns.crw
- access:
    aread: true
  obj: devel.ui.model.view.column.inherits
  obj_access_id: role.devel.models.devel.ui.model.view.column.inherits.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: devel.ui.model.view.column.inherits
  obj_access_id: role.devel.models.devel.ui.model.view.column.inherits.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: devel.ui.model.view.column.inherits
  obj_access_id: role.devel.models.devel.ui.model.view.column.inherits.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: devel.ui.model.view.column.inherits
  obj_access_id: role.devel.models.devel.ui.model.view.column.inherits.crw
