- access:
    aread: true
  obj: wkf.locations
  obj_access_id: role.wkf.models.wkf.locations.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: wkf.locations
  obj_access_id: role.wkf.models.wkf.locations.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: wkf.locations
  obj_access_id: role.wkf.models.wkf.locations.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: wkf.locations
  obj_access_id: role.wkf.models.wkf.locations.crw
- access:
    aread: true
  obj: wkf.workplice.categories
  obj_access_id: role.wkf.models.wkf.workplice.categories.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: wkf.workplice.categories
  obj_access_id: role.wkf.models.wkf.workplice.categories.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: wkf.workplice.categories
  obj_access_id: role.wkf.models.wkf.workplice.categories.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: wkf.workplice.categories
  obj_access_id: role.wkf.models.wkf.workplice.categories.crw
- access:
    aread: true
  obj: wkf.workplace
  obj_access_id: role.wkf.models.wkf.workplace.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: wkf.workplace
  obj_access_id: role.wkf.models.wkf.workplace.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: wkf.workplace
  obj_access_id: role.wkf.models.wkf.workplace.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: wkf.workplace
  obj_access_id: role.wkf.models.wkf.workplace.crw
- access:
    aread: true
  obj: wkf.element.categories
  obj_access_id: role.wkf.models.wkf.element.categories.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: wkf.element.categories
  obj_access_id: role.wkf.models.wkf.element.categories.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: wkf.element.categories
  obj_access_id: role.wkf.models.wkf.element.categories.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: wkf.element.categories
  obj_access_id: role.wkf.models.wkf.element.categories.crw
- access:
    aread: true
  obj: wkf.elements
  obj_access_id: role.wkf.models.wkf.elements.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: wkf.elements
  obj_access_id: role.wkf.models.wkf.elements.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: wkf.elements
  obj_access_id: role.wkf.models.wkf.elements.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: wkf.elements
  obj_access_id: role.wkf.models.wkf.elements.crw
- access:
    aread: true
  obj: wkf.routes
  obj_access_id: role.wkf.models.wkf.routes.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: wkf.routes
  obj_access_id: role.wkf.models.wkf.routes.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: wkf.routes
  obj_access_id: role.wkf.models.wkf.routes.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: wkf.routes
  obj_access_id: role.wkf.models.wkf.routes.crw
- access:
    aread: true
  obj: wkf.jobs
  obj_access_id: role.wkf.models.wkf.jobs.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: wkf.jobs
  obj_access_id: role.wkf.models.wkf.jobs.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: wkf.jobs
  obj_access_id: role.wkf.models.wkf.jobs.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: wkf.jobs
  obj_access_id: role.wkf.models.wkf.jobs.crw
- access:
    aread: true
  obj: wkf.job.history
  obj_access_id: role.wkf.models.wkf.job.history.readonly
- access:
    acreate: true
    aread: true
    awrite: true
  obj: wkf.job.history
  obj_access_id: role.wkf.models.wkf.job.history.nodrop
- access:
    acreate: true
    aexecute: true
    aread: true
    aunlink: true
    awrite: true
  obj: wkf.job.history
  obj_access_id: role.wkf.models.wkf.job.history.full
- access:
    acreate: true
    aexecute: true
    aread: true
    awrite: true
  obj: wkf.job.history
  obj_access_id: role.wkf.models.wkf.job.history.crw
